chore/ci: update CI scripts and readme file
maidsafe/accumulator pull request #69
Opened 2017-02-27 16:02 UTC by nbaksalyar

2017-02-27 16:02 UTC, maidsafe-highfive commented
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @Fraser999 (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

2017-02-27 16:19 UTC, ustulation requested changes

2017-02-27 16:19 UTC, ustulation commented on README.md
> +| [API Docs](http://docs.rs/accumulator/) | [MaidSafe website](https://maidsafe.net) | [SAFE Dev Forum](https://forum.safedev.org) | [SAFE Network Forum](https://safenetforum.org) |
better to move it after `crates` column, call it `Documentation` and provide a badge image like here: https://github.com/maidsafe/safe_client_libs/blob/28978cd10aad433332950284a49e96d881242ef9/safe_core/README.md

2017-03-02 16:29 UTC, ustulation requested changes

2017-03-02 16:29 UTC, ustulation commented on Cargo.toml
>  [package]
Why does this toml still have clippy mentioned. That's one of the main points of this PR - to upade CI scripts to not require clippy in-band. Pls go through lib.rs and every other file like tomls etc where changes need to be made. And in other similar PRs too.

2017-03-03 12:55 UTC, ustulation approved these changes

2017-03-03 12:55 UTC, merged